import { StyleSheet } from "react-native-unistyles";

export const styles = StyleSheet.create((theme) => ({
  container: { flex: 1, minHeight: 0, backgroundColor: theme.colors.background },
  header: {
    padding: theme.spacing[3],
    gap: theme.spacing[1],
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: theme.colors.border,
  },
  row: { flexDirection: "row", alignItems: "center", flexWrap: "wrap", gap: theme.spacing[1] },
  spread: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: theme.spacing[2],
  },
  grow: { flex: 1, minWidth: 0 },
  title: { color: theme.colors.foreground, fontSize: theme.fontSize.sm, fontWeight: "600" },
  muted: { color: theme.colors.foregroundMuted, fontSize: theme.fontSize.sm },
  text: { color: theme.colors.foreground, fontSize: theme.fontSize.base, lineHeight: 22 },
  error: { color: theme.colors.destructive, fontSize: theme.fontSize.sm },
  success: { color: theme.colors.success, fontSize: theme.fontSize.sm },
  notice: { padding: theme.spacing[3], gap: theme.spacing[2] },
  center: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    padding: theme.spacing[4],
    gap: theme.spacing[3],
  },
  messages: { padding: theme.spacing[3], gap: theme.spacing[4] },
  assistant: { alignSelf: "stretch", gap: theme.spacing[1] },
  user: {
    alignSelf: "flex-end",
    maxWidth: "94%",
    borderRadius: theme.borderRadius.md,
    padding: theme.spacing[3],
    backgroundColor: theme.colors.surface2,
    gap: theme.spacing[1],
  },
  proposal: {
    borderWidth: 1,
    borderColor: theme.colors.borderAccent,
    borderRadius: theme.borderRadius.md,
    padding: theme.spacing[3],
    gap: theme.spacing[2],
    backgroundColor: theme.colors.surface1,
  },
  status: {
    padding: theme.spacing[3],
    borderRadius: theme.borderRadius.md,
    backgroundColor: theme.colors.surface1,
    gap: theme.spacing[2],
  },
  input: {
    alignSelf: "stretch",
    minHeight: 72,
    maxHeight: 200,
    fontSize: theme.fontSize.base,
    color: theme.colors.foreground,
    textAlignVertical: "top",
    padding: theme.spacing[3],
    backgroundColor: theme.colors.surface1,
    borderRadius: theme.borderRadius.md,
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  proposalInput: {
    minHeight: 100,
    maxHeight: 240,
    fontSize: theme.fontSize.base,
    color: theme.colors.foreground,
    textAlignVertical: "top",
    padding: theme.spacing[2],
    backgroundColor: theme.colors.background,
    borderRadius: theme.borderRadius.sm,
  },
  composer: {
    padding: theme.spacing[3],
    gap: theme.spacing[2],
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: theme.colors.border,
    backgroundColor: theme.colors.background,
  },
  selector: {
    flexDirection: "row",
    alignItems: "center",
    padding: theme.spacing[2],
    minHeight: 36,
    maxWidth: "100%",
    borderRadius: theme.borderRadius.sm,
    backgroundColor: theme.colors.surface1,
  },
  reference: {
    borderLeftWidth: 2,
    borderLeftColor: theme.colors.borderAccent,
    paddingLeft: theme.spacing[2],
    gap: theme.spacing[1],
  },
}));
